In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
from shapely import wkt

# Geometry and Database

- Import TPS (National)
- Sanity Check (Checking TPS code and compared it with Kemendagri Kelurahan Code)
- Merge join to geometry to TPS  dataset
- Exporting into new DKI CSV

In [2]:
# reading dataframe
df = pd.read_csv('D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/PILPRES_2024-04-18.09-15.csv')
df.shape

(823236, 27)

In [3]:
# Slicing the first 10 characters from each entry in the 'TPS' column
df['TPS_Sliced'] = df['tps'].str[:10]
df.head()

,tps,paslon01,paslon02,paslon03,total_suara_paslon,suara_sah,suara_lebih,suara_tidak_sah,total_suara,img1,...,jumlah_pemilih_dpt,pengguna_dpt_lk,pengguna_dpt_pr,pengguna_dptb_lk,pengguna_dptb_pr,pengguna_dpk_lk,pengguna_dpk_pr,jumlah_pengguna_lk,jumlah_pengguna_pr,TPS_Sliced
0,3578091006050,0,0,0,0,0,0,0,0,-,...,0,0,0,0,0,0,0,0,0,3578091006
1,3211142006010,40,136,7,183,183,0,4,187,https://sirekap-obj-formc.kpu.go.id/5d0d/pemil...,...,200,95,89,1,0,1,1,97,90,3211142006
2,3202111001030,70,124,15,209,209,0,5,214,https://sirekap-obj-formc.kpu.go.id/872e/pemil...,...,264,95,118,0,0,1,0,96,118,3202111001
3,3202112009022,0,0,0,0,0,0,0,0,-,...,0,0,0,0,0,0,0,0,0,3202112009
4,7604112003005,43,145,4,192,192,0,4,196,https://sirekap-obj-formc.kpu.go.id/7098/pemil...,...,218,98,97,0,0,1,0,99,97,7604112003

In [4]:
# Sanity check of tps number using Kelurahan Ancol
count = (df['TPS_Sliced'] == '3172051003').sum()

# Print the count
print(count)

82

In [5]:
# Aggregating df by TPS_Sliced column to get counts per Kelurahan
df_agg = df.groupby('TPS_Sliced').sum()

# Reset the index to have 'TPS_Sliced' as a column
df_agg = df_agg.reset_index()
df_agg

C:\Users\irsra\AppData\Local\Temp\ipykernel_24184\2131208171.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_agg = df.groupby('TPS_Sliced').sum()

,TPS_Sliced,paslon01,paslon02,paslon03,total_suara_paslon,suara_sah,suara_lebih,suara_tidak_sah,total_suara,pengguna_dpt,...,pemilih_dpt_pr,jumlah_pemilih_dpt,pengguna_dpt_lk,pengguna_dpt_pr,pengguna_dptb_lk,pengguna_dptb_pr,pengguna_dpk_lk,pengguna_dpk_pr,jumlah_pengguna_lk,jumlah_pengguna_pr
0,1101012001,555,94,15,664,664,0,8,672,732,...,458,873,343,389,0,4,6,3,348,397
1,1101012002,447,62,8,517,517,0,7,524,511,...,282,562,251,260,7,4,2,0,260,264
2,1101012003,361,56,7,424,424,0,9,433,427,...,239,476,204,223,0,1,2,3,206,227
3,1101012004,297,33,6,336,336,0,1,337,336,...,186,363,164,172,0,0,1,0,165,172
4,1101012015,617,97,5,719,719,0,7,726,704,...,408,803,342,362,6,9,4,3,352,374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83854,99BA010001,386,667,1044,2097,2097,0,54,2151,2006,...,2960,5358,911,1095,53,68,10,14,974,1177
83855,99BB010001,151,244,330,725,725,0,14,739,686,...,621,887,196,490,17,30,2,4,215,524
83856,99BC010001,16,58,36,110,110,0,4,114,76,...,40,158,49,27,34,3,1,0,84,30
83857,99BD010001,59,77,67,203,203,0,4,207,166,...,78,235,110,56,4,3,23,11,137,70
83858,99BE010001,18,19,31,68,68,0,2,70,60,...,52,68,11,49,1,9,0,0,12,58

In [12]:
#Creating DKI TPS csv file
df_dki = df_agg[df_agg['TPS_Sliced'].str.startswith('31')]

# Display the resulting DataFrame
df_dki

,TPS_Sliced,paslon01,paslon02,paslon03,total_suara_paslon,suara_sah,suara_lebih,suara_tidak_sah,total_suara,pengguna_dpt,...,pemilih_dpt_pr,jumlah_pemilih_dpt,pengguna_dpt_lk,pengguna_dpt_pr,pengguna_dptb_lk,pengguna_dptb_pr,pengguna_dpk_lk,pengguna_dpk_pr,jumlah_pengguna_lk,jumlah_pengguna_pr
25546,3101011001,1410,1942,631,3983,3983,0,79,4062,4031,...,2512,5025,1973,2058,41,19,18,12,1919,1966
25547,3101011002,1894,2750,745,5389,5345,44,133,5478,5102,...,2603,6360,2862,2240,382,18,14,18,3260,2276
25548,3101011003,658,827,201,1686,1686,0,34,1720,1669,...,980,1953,818,851,20,10,10,11,848,871
25549,3101021001,783,610,138,1531,1531,0,33,1564,1479,...,866,1756,731,748,47,19,9,10,787,777
25550,3101021002,1527,1597,381,3505,3515,-10,75,3590,3527,...,2002,3994,1700,1827,24,22,7,9,1733,1888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25808,3175101004,4162,4574,1410,10146,7747,2399,116,7863,7506,...,4678,9048,3519,3987,30,29,30,41,3579,4057
25809,3175101005,2834,2720,851,6405,2870,3535,47,2917,2614,...,1644,3221,1235,1379,19,21,17,15,1271,1415
25810,3175101006,2270,2803,689,5762,3130,2821,40,3170,2906,...,1876,3627,1367,1539,9,5,17,27,1393,1569
25811,3175101007,14386,13582,3655,31623,19525,12337,273,19563,19553,...,12000,23329,9280,10262,51,52,91,101,9547,10838
25812,3175101008,3262,3428,1140,7830,3070,4760,39,3109,3098,...,1988,3855,1436,1657,22,23,14,14,1472,1694

In [6]:
# Import basemap
gdf = gpd.read_file('D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DESA_KELURAHAN_BY_PROVINCE/DKI Jakarta_DESA_KELURAHAN.geojson')
gdf.head()

,KODE_KEL_DESA,KODE_KEC,KODE_KAB_KOTA,KODE_PROVINSI,NAMA_KEL_DESA,NAMA_KECAMATAN,NAMA_KAB_KOTA,NAMA_PROVINSI,LUAS_HA,LUAS_SQKM,KODE,geometry
0,31.72.05.1003,31.72.05,31.72,31,Ancol,Pademangan,Kota Administrasi Jakarta Utara,DKI Jakarta,826.183438,8.261834,3172051003,"POLYGON Z ((42105.862 9322466.466 0.000, 42083..."
1,31.73.04.1007,31.73.04,31.73,31,Angke,Tambora,Kota Administrasi Jakarta Barat,DKI Jakarta,79.870229,0.798702,3173041007,"POLYGON Z ((35010.979 9318562.522 0.000, 35010..."
2,31.75.04.1005,31.75.04,31.75,31,Balekambang,Kramatjati,Kota Administrasi Jakarta Timur,DKI Jakarta,169.635973,1.696360,3175041005,"POLYGON Z ((41570.433 9305229.563 0.000, 41551..."
3,31.75.03.1003,31.75.03,31.75,31,Bali Mester,Jatinegara,Kota Administrasi Jakarta Timur,DKI Jakarta,67.550190,0.675502,3175031003,"POLYGON Z ((41889.209 9311621.356 0.000, 41890..."
4,31.75.10.1006,31.75.10,31.75,31,Bambu Apus,Cipayung,Kota Administrasi Jakarta Timur,DKI Jakarta,354.500695,3.545007,3175101006,"POLYGON Z ((47778.435 9301610.681 0.000, 47770..."

In [7]:
# Create a new column 'DPT' in gdf without the dots
gdf['KODE_KEL_DESA_INT'] = gdf['KODE_KEL_DESA'].str.replace('.', '', regex=False)

# Ensure both columns are of type string and remove any leading/trailing spaces
gdf['KODE_KEL_DESA_INT'] = gdf['KODE_KEL_DESA_INT'].astype(str).str.replace(r'\D', '', regex=True).str.strip()

# Merging
gdf_dpt = pd.merge(gdf, df_agg, left_on='KODE_KEL_DESA_INT', right_on ='TPS_Sliced', how='left')
gdf_dpt

,KODE_KEL_DESA,KODE_KEC,KODE_KAB_KOTA,KODE_PROVINSI,NAMA_KEL_DESA,NAMA_KECAMATAN,NAMA_KAB_KOTA,NAMA_PROVINSI,LUAS_HA,LUAS_SQKM,...,pemilih_dpt_pr,jumlah_pemilih_dpt,pengguna_dpt_lk,pengguna_dpt_pr,pengguna_dptb_lk,pengguna_dptb_pr,pengguna_dpk_lk,pengguna_dpk_pr,jumlah_pengguna_lk,jumlah_pengguna_pr
0,31.72.05.1003,31.72.05,31.72,31,Ancol,Pademangan,Kota Administrasi Jakarta Utara,DKI Jakarta,826.183438,8.261834,...,2946,6074,2174,2118,903,113,26,45,2151,2512
1,31.73.04.1007,31.73.04,31.73,31,Angke,Tambora,Kota Administrasi Jakarta Barat,DKI Jakarta,79.870229,0.798702,...,7555,14659,5537,6278,33,23,65,149,5605,6163
2,31.75.04.1005,31.75.04,31.75,31,Balekambang,Kramatjati,Kota Administrasi Jakarta Timur,DKI Jakarta,169.635973,1.696360,...,6123,11964,5189,4897,206,204,56,63,4662,4929
3,31.75.03.1003,31.75.03,31.75,31,Bali Mester,Jatinegara,Kota Administrasi Jakarta Timur,DKI Jakarta,67.550190,0.675502,...,2246,4377,2059,2169,47,66,15,31,1563,1700
4,31.75.10.1006,31.75.10,31.75,31,Bambu Apus,Cipayung,Kota Administrasi Jakarta Timur,DKI Jakarta,354.500695,3.545007,...,1876,3627,1367,1539,9,5,17,27,1393,1569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,31.01.02.1003,31.01.02,31.01,31,Pulau Pari,Kepulauan Seribu Selatan,Administrasi Kepulauan Seribu,DKI Jakarta,168.896794,1.688968,...,1161,2331,1007,992,51,13,6,5,1064,1010
263,31.01.01.1003,31.01.01,31.01,31,Pulau Harapan,Kepulauan Seribu Utara,Administrasi Kepulauan Seribu,DKI Jakarta,467.158381,4.671584,...,980,1953,818,851,20,10,10,11,848,871
264,31.01.01.1002,31.01.01,31.01,31,Pulau Kelapa,Kepulauan Seribu Utara,Administrasi Kepulauan Seribu,DKI Jakarta,114.851021,1.148510,...,2603,6360,2862,2240,382,18,14,18,3260,2276
265,31.01.01.1001,31.01.01,31.01,31,Pulau Panggang,Kepulauan Seribu Utara,Administrasi Kepulauan Seribu,DKI Jakarta,92.274844,0.922748,...,2512,5025,1973,2058,41,19,18,12,1919,1966
266,31.01.02.1002,31.01.02,31.01,31,Pulau Tidung,Kepulauan Seribu Selatan,Administrasi Kepulauan Seribu,DKI Jakarta,104.788110,1.047881,...,2002,3994,1700,1827,24,22,7,9,1733,1888

In [8]:
gdf_dpt.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 267 entries, 0 to 266
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   KODE_KEL_DESA       267 non-null    object
 1   KODE_KEC            267 non-null    object
 2   KODE_KAB_KOTA       267 non-null    object
 3   KODE_PROVINSI       267 non-null    object
 4   NAMA_KEL_DESA       267 non-null    object
 5   NAMA_KECAMATAN      267 non-null    object
 6   NAMA_KAB_KOTA       267 non-null    object
 7   NAMA_PROVINSI       267 non-null    object
 8   LUAS_HA             267 non-null    float64
 9   LUAS_SQKM           267 non-null    float64
 10  KODE                267 non-null    object
 11  geometry            267 non-null    geometry
 12  KODE_KEL_DESA_INT   267 non-null    object
 13  TPS_Sliced          267 non-null    object
 14  paslon01            267 non-null    int64
 15  paslon02            267 non-null    int64
 16  paslon03            267 non-null    int64
 17  total_suara_paslon  267 non-null    int64
 18  suara_sah           267 non-null    int64
 19  suara_lebih         267 non-null    int64
 20  suara_tidak_sah     267 non-null    int64
 21  total_suara         267 non-null    int64
 22  pengguna_dpt        267 non-null    int64
 23  pengguna_dptb       267 non-null    int64
 24  pengguna_dpk        267 non-null    int64
 25  jumlah_pengguna     267 non-null    int64
 26  pemilih_dpt_lk      267 non-null    int64
 27  pemilih_dpt_pr      267 non-null    int64
 28  jumlah_pemilih_dpt  267 non-null    int64
 29  pengguna_dpt_lk     267 non-null    int64
 30  pengguna_dpt_pr     267 non-null    int64
 31  pengguna_dptb_lk    267 non-null    int64
 32  pengguna_dptb_pr    267 non-null    int64
 33  pengguna_dpk_lk     267 non-null    int64
 34  pengguna_dpk_pr     267 non-null    int64
 35  jumlah_pengguna_lk  267 non-null    int64
 36  jumlah_pengguna_pr  267 non-null    int64
dtypes: float64(2), geometry(1), int64(23), object(11)
memory usage: 79.3+ KB

In [9]:
#Exporting into polygon
output_file_path = 'D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DKI.geojson'
gdf_dpt.to_file(output_file_path, driver='GeoJSON')
print(f"GeoDataFrame exported to {output_file_path}")

GeoDataFrame exported to D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DKI.geojson

In [13]:
#Exporting DF_DKIoutput_file_path = 'D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DKI.geojson'
output_csv_path = 'D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DKI.csv'
df_dki.to_csv(output_csv_path, index=False)
print(f"DataFrame exported to {output_csv_path}")

DataFrame exported to D:/Files/6. Work/3. Freelance/1. Datakota/2. Politico/politico-master/politico-master/data/DKI.csv